STAMP-project/dspot

- .travis.yml
- src/main/java/fr/inria/diversify/dspot/Amplification.java
- src/main/java/fr/inria/diversify/dspot/AmplificationHelper.java
- src/main/java/fr/inria/diversify/dspot/DSpot.java
- src/main/java/fr/inria/diversify/dspot/TestSelector.java
- src/main/java/fr/inria/diversify/dspot/amp/StatementAdderOnAssert.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/AssertGenerator.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/MethodAssertGenerator.java
- src/main/java/fr/inria/diversify/mutant/MutantGenerator.java
- src/test/java/fr/inria/diversify/dspot/DSpotTest.java
- src/test/java/fr/inria/diversify/dspot/amp/TestMethodCallAdderTest.java
- src/test/java/fr/inria/diversify/dspot/assertGenerator/AssertGeneratorTest.java
- src/test/java/fr/inria/diversify/mutant/MutantGeneratorTest.java
Refactor the amplification loop.
Next step is the refactor of the test selector. We need an interface and remove dependencies between test selector and amplifier. We will be able to add easily pit mutation coverage selection after that (almost done in local).
> Refactor amplification loop

- src/main/java/fr/inria/diversify/dspot/AmplificationHelper.java
- src/main/java/fr/inria/diversify/mutant/pit/PitRunner.java
- src/main/java/fr/inria/stamp/JSAPOptions.java
throught the InputConfiguration
support -DadditionnalClasspathElements and -DexcludedClasses in pit runner.
-DexcludedClasses  will be use to discard test cases that are not passing from dspot, such as test that use relative path (until we find a fix).
> Improve pit runner

- src/main/java/fr/inria/diversify/dspot/Amplification.java
- src/main/java/fr/inria/diversify/dspot/AmplificationHelper.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/AssertGenerator.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/AssertGeneratorHelper.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/MethodAssertGenerator.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/MethodsAssertGenerator.java
- src/test/java/fr/inria/diversify/dspot/assertGenerator/MethodsAssertGeneratorTest.java
- src/test/java/fr/inria/stamp/MainTest.java
Compiling and running all the generated test case, and not one by one (such as the MethodAssertGenerator).
On DSpotTest, it decreases the computation time from 3s to 1.3s
Adds a AssertGeneratorHelper
> feat: add MethodsAssertGenerator

- src/main/java/fr/inria/diversify/dspot/Amplification.java
- src/main/java/fr/inria/diversify/dspot/AmplificationHelper.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/AssertGenerator.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/MethodAssertGenerator.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/MethodsAssertGenerator.java
- src/main/java/fr/inria/diversify/dspot/support/DSpotCompiler.java
- src/main/java/fr/inria/diversify/dspot/value/ValueCreator.java
- src/main/java/fr/inria/diversify/testRunner/TestCompiler.java
- src/test/java/fr/inria/diversify/dspot/DSpotCompilerTest.java
- src/test/java/fr/inria/diversify/dspot/DSpotTest.java
- src/test/java/fr/inria/diversify/dspot/amplifier/TestStatementAdderOnAssert.java
- src/test/java/fr/inria/diversify/dspot/amplifier/TestValueCreator.java
- src/test/java/fr/inria/diversify/mutant/pit/PitTest.java
- src/test/resources/sample/src/test/java/fr/inria/compiler/TestCompiler.java
Hello, 
The PR #78 introduced a bug: when a test case was uncompilable, dspot skipped the whole iteration.
Now, we discard test cases that produce compilation error and recompile after that.
> Fix assertgenerator

- src/main/java/fr/inria/diversify/dspot/AmplificationHelper.java
When dspot generates too much test (more than 200), the map of parents was not updated and keep traces of unused test cases (and theirs parent). 
Now, it used an intermediate map, and update the parent map with only the test cases that are kept.
> optim memory

- src/main/java/fr/inria/diversify/automaticbuilder/AutomaticBuilderFactory.java
- src/main/java/fr/inria/diversify/dspot/DSpot.java
- src/main/java/fr/inria/diversify/dspot/selector/PitMutantScoreSelector.java
- src/main/java/fr/inria/stamp/Configuration.java
- src/main/java/fr/inria/stamp/JSAPOptions.java
- src/main/java/fr/inria/stamp/Main.java
- src/test/java/fr/inria/diversify/automaticbuilder/AutomaticBuilderFactoryTest.java
- src/test/java/fr/inria/diversify/mutant/pit/PitTest.java
Hi @danglotb, I've made some configuration/input arguments stuff to let DSpot users select their desired Automatic Builder. A factory is used to instantiate the builder, according to the user choice. What do you think about this solution?
> Gradle projects support

- src/main/java/fr/inria/diversify/automaticbuilder/GradleAutomaticBuilder.java
- src/main/java/fr/inria/diversify/mutant/pit/GradlePitTaskAndOptions.java
- src/test/resources/test-projects/test-projects.properties
Hi @danglotb , I moved jvm options and timeout option management to the target project properties. Now if you want to use these two options within Gradle Projects, you have to add them to that file. You can see an example below in the test-projects.properties file (I put some comments to explain). I run all tests locally and in Travis, and everything went fine. In a couple of days I will add also the support to descartes mutators.
> Gradle Projects support: jvm options and timeout option to dspot project properties

- dspot/src/main/java/fr/inria/diversify/dspot/Amplification.java
The same 33/37 tests passed so I assume this commit did not break anything.
> fix #336: keep partially failing amplified classes

- README.md
- dspot/src/test/java/fr/inria/diversify/automaticbuilder/MavenAutomaticBuilderTest.java
We cannot give `*` as filter since when we do that PIT would mutate itself.
When the maven goals are called using `filter=*`, PIT throws the following errors:
```
[ERROR] Failed to execute goal org.pitest:pitest-maven:1.3.0:mutationCoverage (default-cli) on project example:
Execution default-cli of goal org.pitest:pitest-maven:1.3.0:mutationCoverage failed:
The supplied filter would cause PIT to try and mutate itself. 
This will lead to many wasted hours of confusion and debugging. 
You have better things to do with your life so please don't do this again.
```
Therefore, I updated the documentation according to this: users must provide a correct `filter` or have a correct packages/pom according to maven conventions.
> docs: fix the documentation according to the usage of PIT

- dspot-maven/src/main/java/eu/stamp_project/DSpotMojo.java
- dspot/src/main/java/eu/stamp_project/program/InputConfiguration.java
Hi,
This pull request allows building the instance of `InputConfiguration` from a `java.util.Properties` object.
I updated the `DSpotMojo` consequently: the path to the properties file is no longer mandatory, but still usable to set others property.
It remains to retrieve information from the `pom.xml`, like the base dir and folders of sources, binaries, and resources for instance. And test the `DSpotMojo` using different ways to launch it: command line, unit test etc...
@nicolabertazzo @spookyvale, could you please review the current changes and tell me if everything is good or what is missing? Thank you.
> Open input configuration

- dspot/src/main/java/eu/stamp_project/dspot/assertgenerator/AssertionRemover.java
- dspot/src/test/java/eu/stamp_project/dspot/assertgenerator/AssertionRemoverTest.java
- dspot/src/test/resources/sample/src/test/java/fr/inria/sample/TestClassWithAssert.java
With this, we have:
```java
@Test
public void test3_exceptionCatch() throws Exception {
try {
ClassThrowException cl = new ClassThrowException();
cl.throwException();
junit.framework.TestCase.fail("test3 should have thrown Exception");
} catch (java.lang.Exception eee) {
}
}
```
and obtain:
```java
@Test
public void test3_exceptionCatch() throws Exception {
ClassThrowException cl = new ClassThrowException();
cl.throwException();
}
```
I think it is good because after this, **DSpot** will executes it and observe that the test fails (because of the `cl.throwException();`) and then wrap it with a standard try/catch block and fail statement. In the processus of Amplification, I think this can lead to a better exploration because in one hand if an I-Ampl lead to set the program into a …
> feat: Remove try catch fail before assertion FIX #533

- dspot/pom.xml
- dspot/src/main/java/eu/stamp_project/dspot/Amplification.java
- dspot/src/main/java/eu/stamp_project/dspot/budget/NoBudgetizer.java
- dspot/src/main/java/eu/stamp_project/utils/AmplificationHelper.java
This PR solves some side effects of my previous optimization PR that uses a dictionary that holds references of cloned CtMethods to original test methods. As a consequence of that optimization:
- the number of methods hold in the dictionary scale up to provoke a memory heap exception
- in parallel execution paths (for some parallel streams), the dictionary got corrupted, causing the no resolution of some methods, which in turn, force TestFramework to resolve for some cloned methods (this should not happen).
This PR fixed this issues by:
- synchronizing the access to the dictionary
- removing dictionary entries for all methods discarded by DSpot after input amplification.
This PR also upgrades the dependency on test-runner to version 2.0.7.
> Optimization#3

- dspot/src/main/java/eu/stamp_project/utils/DSpotUtils.java
use now the complete classpath to compile the newly amplified test class
> fix: print the amplified test class with import FIX #745

- dspot/src/main/java/eu/stamp_project/dspot/DSpot.java
- dspot/src/main/java/eu/stamp_project/test_framework/TestFramework.java
- dspot/src/main/java/eu/stamp_project/test_framework/TestFrameworkSupport.java
- dspot/src/main/java/eu/stamp_project/test_framework/implementations/AssertJTestFramework.java
- dspot/src/main/java/eu/stamp_project/test_framework/implementations/GoogleTruthTestFramework.java
- dspot/src/main/java/eu/stamp_project/test_framework/implementations/NoneTestFrameworkSupport.java
- dspot/src/main/java/eu/stamp_project/test_framework/implementations/junit/JUnit3Support.java
- dspot/src/main/java/eu/stamp_project/test_framework/implementations/junit/JUnitSupport.java
Experimenting DSpot in some Supersede IF test classes (suites) I faced some NPE errors caused by TestRunner problems to execute the test and obtain an nonexistent serialized TestResult.ser.
So I debugged these experiments and realized that the _MethodFilter_ in _JUnit4Runner_ was receiving in its method _shouldRun_ a wrong _Description_ for a test class with not test methods. So, inspecting my Supersede IF test suite I realized it was ignored by @Ignore annotation. Despite that, DSpot was trying to amplify the test. So, I've created this PR that filters out all JUnit4 @Ignored and JUnit5 @Disable test classes, reporting them in logs (INFO).
I will create a bug report associated to this PR.
> Fix: detection(filtering out) of @Ignored (JUnit4) or @Disabled (JUnit5) test suites before proceeding with amplification

- dspot/src/main/java/eu/stamp_project/utils/options/AmplifierEnum.java
- kubernetes-support/Dpipeline-dockerimage/Dockerfile
- kubernetes-support/Dpipeline-dockerimage/Dpipeline_worker.py
- kubernetes-support/queue-for-buildids/publisher.py
Hi :), this is a broken down PR for this original PR (#832). 
How to use:
First pull and run the ActiveMQ server image
```
docker pull webcenter/activemq:5.14.3
docker run -d --net=host webcenter/activemq:5.14.3
```
Then go to the server page to make sure that it's up [http://localhost:8161](http://localhost:8161).
Go into ```kubernetes-support/Dpipeline-dockerimage``` and build the ```dspot-pipeline``` image and run it.
```
cd kubernetes-support/Dpipeline-dockerimage
docker build -t dspot-pipeline .
docker run --net=host -e ACTIVEMQ_HOST=localhost dspot-pipeline
```
Now you can see in your server page that there is one consumer on your ```Dpipeline``` queue. Next is to use publisher.py to send build id for the pipeline to do some work.
```
cd kubernetes-support/queue-for-buildids
python …
```
> FEAT: Add dspot-pipeline dockerimage (#802)

- README.md
- dspot-maven/src/main/java/eu/stamp_project/DSpotMojo.java
- dspot/src/main/java/eu/stamp_project/dspot/amplifier/MethodAdderOnExistingObjectsAmplifier.java
- dspot/src/main/java/eu/stamp_project/dspot/amplifier/MethodDuplicationAmplifier.java
- dspot/src/main/java/eu/stamp_project/utils/options/AmplifierEnum.java
- dspot/src/test/java/eu/stamp_project/MainTest.java
- dspot/src/test/java/eu/stamp_project/dspot/DSpotMockedTest.java
- dspot/src/test/java/eu/stamp_project/dspot/DSpotTest.java
- dspot/src/test/java/eu/stamp_project/dspot/amplifier/MethodAdderOnExistingObjectsAmplifierTest.java
- dspot/src/test/java/eu/stamp_project/dspot/amplifier/TestMethodCallAdder.java
- dspot/src/test/java/eu/stamp_project/dspot/assertgenerator/AssertGeneratorHelperTest.java
- dspot/src/test/java/eu/stamp_project/dspot/budget/SimpleBudgetizerTest.java
The old names are still usable for now.
> Refactor: methodadd methodgen amplifiers FIX #844

- kubernetes-support/Dpipeline-dockerimage/Dockerfile
- kubernetes-support/Dpipeline-dockerimage/Dpipeline_worker.py
- kubernetes-support/Dpipeline-dockerimage/settings.xml
- kubernetes-support/queue-for-buildids/publisher.py
This PR adds needed elements to execute dockerized DSpot behind a corporate proxy. Tested with Engineering Group corporate proxy. By default needed elements are disabled (execution with no proxy around)
> Dockerized dspot execution behind corporate proxy

- dspot/src/main/java/eu/stamp_project/dspot/selector/ChangeDetectorSelector.java
- dspot/src/main/java/eu/stamp_project/dspot/selector/JacocoCoverageSelector.java
- dspot/src/main/java/eu/stamp_project/dspot/selector/PitMutantScoreSelector.java
- dspot/src/main/java/eu/stamp_project/dspot/selector/TakeAllSelector.java
- dspot/src/main/java/eu/stamp_project/utils/pit/AbstractParser.java
- dspot/src/main/java/eu/stamp_project/utils/report/output/selector/TestSelectorElementReportImpl.java
- dspot/src/main/java/eu/stamp_project/utils/report/output/selector/TestSelectorReportImpl.java
- dspot/src/test/java/eu/stamp_project/utils/pit/PitCSVParserAndResultTest.java
- dspot/src/test/java/eu/stamp_project/utils/pit/PitXMLParserAndResultTest.java
@borisbaldassari @monperrus WDYT ?
The idea is to save keep the string representation of the reports and output them in the output directory of DSpot.
You will have the baseline (before amplification), during and after amplification.
For now, I implemented it only for Descartes (PitMutantScoreSelector).
The report files are named like this: `full.qualified.name.of.test.class_test_criterion_report_<index>`, where `<index>` is the index of the reports in the list of reports, _e.g._ `0` for the baseline.
> Feat: keep intermediate reports FIX #911

- .travis/travis-coverage.sh
- .travis/travis-openjdk8.sh
- dspot/src/test/java/eu/stamp_project/dspot/common/automaticbuilder/gradle/GradleAutomaticBuilderTest.java
- dspot/src/test/java/eu/stamp_project/dspot/common/collector/mongodb/MongodbCollectorTest.java
Problem: a simple `mvn test` fails, because of complex dependencies for integration tests, see https://ci.inria.fr/sos/job/dspot/14/console
Solution: add a flag `doIntegrationTests` disabled by default
> fix default maven test

- dspot/src/main/java/eu/stamp_project/dspot/common/report/output/selector/takeall/json/TestClassJSON.java
- dspot/src/main/java/eu/stamp_project/dspot/selector/TakeAllSelector.java
- dspot/src/test/java/eu/stamp_project/dspot/selector/TakeAllSelectorTest.java
When using the TakeAllSelector, a null pointer exception appears in the output log.
Example excerpt from the log from running `MainTest..testMainWithEmptyTestMethods()` on master:
```
[INFO] 2020-06-01 11:10:10 DSpot - elapsedTime 1310
java.lang.NullPointerException
at eu.stamp_project.dspot.common.report.output.selector.TestSelectorElementReportImpl.getReportForCollector(TestSelectorElementReportImpl.java:42)
at eu.stamp_project.dspot.common.configuration.AmplificationSetup.postAmplification(AmplificationSetup.java:84)
at eu.stamp_project.dspot.DSpot.run(DSpot.java:54)
at eu.stamp_project.Main.main(Main.java:20)
at eu.stamp_project.MainTest.testMainWithEmptyTestMethods(MainTest.java:164)
at ...
[ERROR] 2020-06-01 11:10:10 DSpot - Something bad happened during the report fot …
```
> Fix nullpointer exception when reporting with TakeAllSelector

- README.md
- dspot/src/main/java/eu/stamp_project/dspot/DSpot.java
- dspot/src/main/java/eu/stamp_project/dspot/common/configuration/DSpotState.java
- dspot/src/main/java/eu/stamp_project/dspot/common/configuration/InitializeDSpot.java
- dspot/src/main/java/eu/stamp_project/dspot/common/configuration/UserInput.java
- dspot/src/test/java/eu/stamp_project/MainTest.java
Adds an option to skip assertion generation and only perform input amplification on the test cases.
> Feat: Add option to only perform input amplification

- .travis/travis-prettifier.sh
The job errored because there was too much log output.
I've set the pip install to quiet and now the job should no longer be aborted 😃
> fix travis build - prettifier job

- README.md
Drive-by doc improvement suggestion - linking in IntelliJ plugin developed by @lacinoire.
> Doc: add link to DSpot IntelliJ plugin

- dspot/pom.xml
log4j1.2 is not [supported anymore](http://logging.apache.org/log4j/1.2/index.html) since 2015
> refactor: remove dependency to unsupported library log4j 1.2
