STAMP-project/dspot

- src/main/java/fr/inria/diversify/dspot/amp/TestDataMutator.java
- src/test/java/fr/inria/diversify/dspot/amp/TestDataMutatorTest.java
- src/test/resources/amp/LiteralMutation.java
- src/test/resources/mutation/LiteralMutation.java
* add test for TestDataMutator
* fix bound of random: using lits (same literals such as the muted) instead of literals (all type)
> Test data mutator

- .travis.yml
- README.md
- pom.xml
- src/test/java/fr/inria/diversify/dspot/assertGenerator/MethodAssertGeneratorTest.java
* add @Ignore to flaky test
* update spoon version
> setup Jacoco coverage

- src/main/java/fr/inria/diversify/dspot/amp/AmplifierHelper.java
- src/main/java/fr/inria/diversify/dspot/amp/StatementAdd.java
- src/main/java/fr/inria/diversify/dspot/value/ValueType.java
- src/main/java/fr/inria/diversify/utils/CtTypeUtils.java
- src/test/java/fr/inria/diversify/Utils.java
- src/test/java/fr/inria/diversify/dspot/Utils.java
- src/test/java/fr/inria/diversify/dspot/amp/StatementAddTest.java
- src/test/resources/src/statementadd/ClassParameterAmplify.java
- src/test/resources/src/statementadd/ClassTargetAmplify.java
- src/test/resources/test/statementadd/TestClassTargetAmplify.java
With this PR, we will use the new way to test Amplifier. 
The resource project sample won't be necessary any more.
> test: StatementAdd amplificator

- src/main/java/fr/inria/diversify/dspot/Amplification.java
- src/main/java/fr/inria/diversify/dspot/DSpot.java
- src/main/java/fr/inria/diversify/mutant/MutantGenerator.java
- src/main/java/fr/inria/diversify/mutant/pit/PitResult.java
- src/main/java/fr/inria/diversify/mutant/pit/PitResultParser.java
- src/main/java/fr/inria/diversify/mutant/pit/PitRunner.java
- src/test/java/fr/inria/diversify/dspot/DSpotTest.java
- src/test/java/fr/inria/diversify/dspot/MavenAbstractTest.java
- src/test/java/fr/inria/diversify/mutant/MutantGeneratorTest.java
- src/test/java/fr/inria/diversify/mutant/pit/PItTest.java
- src/test/resources/test-projects/pom.xml
We'll need other PR to run the pit mutant selection.
The fix of the failing test case is in #31
> WIP: Pit runner

- pom.xml
- src/main/java/fr/inria/diversify/dspot/Amplification.java
- src/main/java/fr/inria/diversify/dspot/AmplificationHelper.java
- src/main/java/fr/inria/diversify/dspot/amplifier/StatementAdderOnAssert.java
- src/main/java/fr/inria/diversify/dspot/amplifier/TestDataMutator.java
- src/main/java/fr/inria/diversify/dspot/amplifier/TestMethodCallAdder.java
- src/main/java/fr/inria/diversify/dspot/amplifier/TestMethodCallRemover.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/AssertGenerator.java
- src/main/java/fr/inria/diversify/dspot/assertGenerator/MethodAssertGenerator.java
- src/main/java/fr/inria/diversify/dspot/selector/BranchCoverageTestSelector.java
- src/main/java/fr/inria/diversify/dspot/selector/PitMutantScoreSelector.java
- src/main/java/fr/inria/diversify/dspot/support/Counter.java
- src/main/java/fr/inria/diversify/mutant/pit/PitResult.java
- src/main/java/fr/inria/diversify/mutant/pit/PitResultParser.java
- src/main/java/fr/inria/diversify/mutant/pit/PitRunner.java
- src/test/java/fr/inria/diversify/dspot/DSpotTest.java
- src/test/java/fr/inria/diversify/dspot/assertGenerator/AssertGeneratorTest.java
- src/test/java/fr/inria/diversify/dspot/selector/PitScoreMutantSelectorTest.java
- src/test/java/fr/inria/diversify/mutant/pit/PitTest.java
- src/test/resources/test-projects/test-projects.properties
```json
{
"test7_cf141":{
"#AssertionAdded":3,
"#InputAdded":3,
"#MutantKilled":1,
"MutantsKilled":[
{
"ID":"org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_ORDER_ELSE",
"lineNumber":"12",
"location":"charAt"
}
]
},
"test2_cf42":{
"#AssertionAdded":3,
"#InputAdded":3,
"#MutantKilled":1,
"MutantsKilled":[
{
"ID":"org.pitest.mutationtest.engine.gregor.mutators.RemoveConditionalMutator_ORDER_ELSE",
"lineNumber":"12",
"location":"charAt"
}
]
}
}
```
> Json report

- src/main/java/fr/inria/diversify/dspot/DSpot.java
This allows to get specified versions and properties in the pom parent of modules.
> copy the pom parent in case there is one

- src/main/java/fr/inria/stamp/Configuration.java
- src/main/java/fr/inria/stamp/JSAPOptions.java
- src/main/java/fr/inria/stamp/Main.java
> add command line argument to specify the path maven home 

- src/main/java/fr/inria/diversify/dspot/DSpot.java
- src/main/java/fr/inria/diversify/dspot/support/ClassTimeJSON.java
- src/main/java/fr/inria/diversify/dspot/support/ProjectTimeJSON.java
- src/test/java/fr/inria/diversify/dspot/DSpotTest.java
> add time per amplification of class

- src/main/java/fr/inria/diversify/mutant/pit/PitRunner.java
> check that mutations.csv exists

- src/main/java/fr/inria/diversify/dspot/DSpotUtils.java
- src/main/java/fr/inria/diversify/dspot/support/MavenDependenciesResolver.java
- src/test/java/fr/inria/diversify/dspot/support/MavenDependenciesResolverTest.java
> Refactor get dependencies

- src/main/java/fr/inria/diversify/mutant/descartes/DescartesInjector.java
- src/test/java/fr/inria/diversify/mutant/descartes/DescartesTest.java
- src/test/java/fr/inria/diversify/mutant/descartes/PitDescartesTest.java
> fix descartes injector

- src/main/java/fr/inria/diversify/dspot/Amplification.java
- src/main/java/fr/inria/diversify/dspot/AmplificationChecker.java
- src/main/java/fr/inria/diversify/dspot/DSpot.java
- src/test/java/fr/inria/diversify/Utils.java
- src/test/java/fr/inria/diversify/dspot/DSpotMultiplePomTest.java
- src/test/java/fr/inria/diversify/mutant/descartes/PitDescartesTest.java
- src/test/resources/multiple-pom/deep-pom-modules.properties
- src/test/resources/multiple-pom/module-1/module-2-1/pom.xml
- src/test/resources/multiple-pom/module-1/module-2-1/src/main/java/HelloWorld.java
- src/test/resources/multiple-pom/module-1/module-2-1/src/test/java/HelloWorldTest.java
- src/test/resources/multiple-pom/module-1/module-2-2/pom.xml
- src/test/resources/multiple-pom/module-1/module-2-2/src/main/java/HelloWorld.java
- src/test/resources/multiple-pom/module-1/module-2-2/src/test/java/HelloWorldTest.java
- src/test/resources/multiple-pom/module-1/pom.xml
- src/test/resources/multiple-pom/pom.xml
Most of the file added are the resources of test.
> Deep pom modules

- src/main/java/fr/inria/diversify/automaticbuilder/MavenAutomaticBuilder.java
- src/main/java/fr/inria/diversify/dspot/Amplification.java
- src/main/java/fr/inria/diversify/dspot/amplifier/TestDataMutator.java
- src/main/java/fr/inria/diversify/dspot/amplifier/TestMethodCallAdder.java
- src/main/java/fr/inria/diversify/dspot/amplifier/TestMethodCallRemover.java
- src/main/java/fr/inria/diversify/utils/AmplificationChecker.java
- src/main/java/fr/inria/diversify/utils/AmplificationHelper.java
- src/main/java/fr/inria/stamp/JSAPOptions.java
- src/test/java/fr/inria/diversify/dspot/DSpotTest.java
- src/test/java/fr/inria/diversify/dspot/amplifier/TestDataMutatorTest.java
- src/test/resources/sample/src/main/java/fr/inria/amp/LiteralMutation.java
* Fixed the TestDataMutator
* Add distinct on amplified test
* Fix the log
> fix and extends TestDataMutation

- .travis.yml
- dspot/pom.xml
- dspot/src/main/java/fr/inria/diversify/utils/DSpotUtils.java
- dspot/src/test/resources/project-with-resources/project-with-resources.properties
- pom.xml
* add by default `src/main/resources` and `src/test/resources`
* log when an error is produced instead of crash suddenly
> Fix #274 and Fix #276 : Default resources

- dspot/src/main/java/fr/inria/diversify/dspot/selector/CloverCoverageSelector.java
- dspot/src/main/java/fr/inria/diversify/dspot/selector/JacocoCoverageSelector.java
TODO: Select diversity of amplified test, select the best of them
> Fix clover selector

- dspot/src/main/java/fr/inria/diversify/dspot/Amplification.java
- dspot/src/main/java/fr/inria/diversify/dspot/amplifier/StringLiteralAmplifier.java
- dspot/src/main/java/fr/inria/diversify/dspot/selector/CloverCoverageSelector.java
- dspot/src/main/java/fr/inria/diversify/utils/AmplificationHelper.java
- dspot/src/main/java/fr/inria/stamp/JSAPOptions.java
- dspot/src/test/java/fr/inria/diversify/utils/AmplificationHelperTest.java
The idea is, instead of selecting randomly amplified test, we compute the hashcode, and we keep test that have difference between hashcodes.
> Reduction by hashcode

- dspot/src/main/java/fr/inria/diversify/dspot/Amplification.java
- dspot/src/main/java/fr/inria/diversify/dspot/assertGenerator/AssertGenerator.java
- dspot/src/main/java/fr/inria/diversify/dspot/assertGenerator/AssertionRemover.java
- dspot/src/main/java/fr/inria/diversify/dspot/assertGenerator/MethodsAssertGenerator.java
- dspot/src/main/java/fr/inria/diversify/dspot/selector/TakeAllSelector.java
A bit of documentation for key methods
> Documentation

- README.md
major refactoring of readme.
- move content around
- improve text
> update readme to improve the open-source look'n'feel

- dspot/src/main/java/fr/inria/diversify/dspot/DSpot.java
Thanks to @fermenreq for pointing the regression.
> fix: call now amplifyTests on each provided String

- README.md
@jesus-gorronogoitia , @danzone WDYT?
> add "DSpot ecosystem"

- dspot/src/main/java/eu/stamp_project/dspot/DSpot.java
small change to create the json report file correctly also in Win OS
> Win os compatibility

- dspot/src/main/java/eu/stamp_project/clover/CloverExecutor.java
- dspot/src/main/java/eu/stamp_project/dspot/DSpot.java
- dspot/src/main/java/eu/stamp_project/dspot/selector/CloverCoverageSelector.java
- dspot/src/main/java/eu/stamp_project/program/InputConfiguration.java
- dspot/src/main/java/eu/stamp_project/utils/DSpotUtils.java
- dspot/src/test/java/eu/stamp_project/dspot/DSpotMockedTest.java
- dspot/src/test/java/eu/stamp_project/dspot/DSpotSelectionTest.java
- dspot/src/test/java/eu/stamp_project/utils/DSpotUtilsTest.java
> Fix: get all test classes

- dspot/src/main/java/eu/stamp_project/automaticbuilder/MavenAutomaticBuilder.java
> fix: add a joker to the top package

- dspot/src/main/java/eu/stamp_project/automaticbuilder/gradle/GradleAutomaticBuilder.java
- dspot/src/main/java/eu/stamp_project/automaticbuilder/gradle/GradlePitTaskAndOptions.java
- dspot/src/main/java/eu/stamp_project/utils/program/ConstantsProperties.java
- dspot/src/main/java/eu/stamp_project/utils/program/InputConfiguration.java
Hello @pedrovelho, I found several bugs yesterday.
This pr aims at fix them.
Please, retry to amplify the toy test after it has been merged.
> Fix gradle properties and skip compile test

- dspot/src/main/java/eu/stamp_project/dspot/assertgenerator/AssertionRemover.java
- dspot/src/test/java/eu/stamp_project/dspot/assertgenerator/AssertionRemoverTest.java
- dspot/src/test/resources/sample/src/test/java/fr/inria/sample/TestClassWithAssert.java
> Fix: remove assertion lambda no body

- README.md
- dspot-maven/src/main/java/eu/stamp_project/DSpotMojo.java
- dspot/pom.xml
- dspot/src/main/java/eu/stamp_project/automaticbuilder/maven/DSpotPOMCreator.java
- dspot/src/main/java/eu/stamp_project/automaticbuilder/maven/MavenAutomaticBuilder.java
- dspot/src/main/java/eu/stamp_project/dspot/assertgenerator/AssertGenerator.java
- dspot/src/main/java/eu/stamp_project/dspot/selector/PitMutantScoreSelector.java
- dspot/src/main/java/eu/stamp_project/utils/CloneHelper.java
- dspot/src/main/java/eu/stamp_project/utils/compilation/TestCompiler.java
- dspot/src/main/java/eu/stamp_project/utils/options/Configuration.java
- dspot/src/main/java/eu/stamp_project/utils/options/JSAPOptions.java
- dspot/src/main/java/eu/stamp_project/utils/program/InputConfiguration.java
This PR replaces the #775 which is corrupted.
> Optimization#7 Parallel execution of JUnit 4/5 tests

- dspot-web/README.md
Add link for running dspot locally.:)
> Fix: update readme for dspot-web

- dspot-web/Dockerfile
- dspot-web/README.md
- dspot-web/controllers/methods.js
- dspot-web/controllers/pages/about.html
- dspot-web/controllers/pages/index.html
- dspot-web/controllers/pages/repos.html
- dspot-web/controllers/pages/reposTemplate.html
- dspot-web/dspot-web.yaml
- dspot-web/package.json
- dspot-web/public/javascripts/allReposInfo.js
- dspot-web/public/javascripts/recentReposInfo.js
- dspot-web/public/javascripts/reposTemplate.js
- dspot-web/routes/index.js
Hi @monperrus @danglotb :) , final PR for website update . This is the latest version shown on <http://dspot.kth-assert.net/> after some bugfixes during production. After this PR is the updated docker image (would be best if Dspot is released as the latest version for me to add instead of local JAR) .
> Fix: various bugfixes update for website

- kubernetes-support/Dpipeline-dockerimage/Dpipeline_worker.py
- kubernetes-support/queue-for-buildids/publisher.py
> Parallelized dspot minor fixes

- kubernetes-support/Dpipeline-dockerimage/Dockerfile
- kubernetes-support/Dpipeline-dockerimage/Dpipeline_worker.py
@monperrus @danglotb hi :) , I see that there has been some works on the image so I figure that I should add these right now instead of waiting for the release of Dspot 2.2.0 so people can work on the latest image version. This is the image using on <http://dspot.kth-assert.net/>, which have been in production for a while. 
This is also the final PR related to web interface task from myself.
> Fix: update Dspot Docker image for website

- kubernetes-support/Dpipeline-dockerimage/Dockerfile
- kubernetes-support/Dpipeline-dockerimage/Dpipeline_worker.py
@danglotb Hi :) , now we have 2.2.0 release so I took the initiative to update the docker image to download directly instead of local builds.
Also, I redeployed everything just now on <http://dspot.kth-assert.net/> to see if there are any problems since we got some bug reports lately and It seems to be working as usual on my part.
> Fix: update docker image

- .travis/travis-coverage.sh
- .travis/travis-openjdk8.sh
- dspot-prettifier/src/test/java/eu/stamp_project/prettifier/context2name/Context2NameTest.java
- dspot/src/test/java/eu/stamp_project/dspot/common/automaticbuilder/gradle/GradleAutomaticBuilderTest.java
- dspot/src/test/java/eu/stamp_project/dspot/common/collector/mongodb/MongodbCollectorTest.java
finish the job of #943 
(pb https://ci.inria.fr/sos/job/dspot/15/console)
> test: exclude test depending on python from default "mvn test"
